### ISSUE TITLE
Create Content Model

### ISSUE THREAD

**Issue by zaguiini** [Automattic/create-content-model#13]
This project demonstrates how recent WordPress Block developments, such as [Block Bindings](https://developer.wordpress.org/news/2024/02/20/introducing-block-bindings-part-1-connecting-custom-fields/#why-the-block-bindings-api-is-useful) and [Block Variations](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/), will help usher in a new no-code paradigm for creating custom data models.   Our Content Model plugin allows creation of Custom Post Types and Custom fields in the Block Editor.   Related advances are coming in core, such as a[ UI to connect blocks to existing post meta fields in Gutenberg 19.0.](https://make.wordpress.org/core/2024/08/14/whats-new-in-gutenberg-19-0-14-august/#ui-to-connect-blocks-and-custom-fields)

## Scope

This section, heavily inspired by [Shape Up](https://basecamp.com/shapeup/3.3-chapter-12), divides the project into feature scopes, allowing for a quicker, high-level overview of the deliverables.

### Data Type Definition

A "data type" is a combination of the [Custom Post Type](https://developer.wordpress.org/plugins/post-types/registering-custom-post-types/), its default CPT-template, and its post meta fields. A data type is defined in the Block Editor, where a user chooses appropriate blocks and assigns post meta field names to block attributes. All parts of the data type are defined through the Block Editor through intuitive UIs.

```[tasklist]
### Tasks
- [x] Manage CPT and its settings from the Block Editor
- [x] Allow the registration of the CPT template from the Block Editor
- [x] Bind post meta fields to block attributes
- [x] Describe non-visible post meta fields through a Form UI
```

### Data Entry

Clicking "Add new [Data Type Name]" from wp-admin opens the template defined in [Data Type Definition](https://github.com/Automattic/create-content-model/issues/13#Data-Type-Definition.) in the Block Editor, which is ready for data entry. The user can enter content in the blocks and modify block attributes. Upon saving, these bound attributes will be mapped to the post meta fields of the assigned CPT.

```[tasklist]
### Tasks
- [x] Display CPT template when entering the new entry page
- [x] Allow modifying exclusively the value of bound attributes
- [x] Allow filling the non-visible field values through the Form UI
- [x] On save, extract the bound values from block attributes and save them as post meta field values
- [x] On entry edit, hydrate the CPT template with existing data
```

### Front-end Templating

When creating a 10Vmcq36iNEiiFYYy-rzlu9EbZSYb0D3y4JMs36HIRJA-gdoc, the user defines the default CPT-template using blocks. This full template may be used for display on the front-end, however, there are cases where only a subset of blocks should be displayed, for example a customized Query Loop that displays only choice items from the previously defined CPT template.  

The blocks from the CPT template that have [block bindings](https://make.wordpress.org/core/2024/03/06/new-feature-the-block-bindings-api/) will be exposed in the Site Editor Block Inserter as [block variations](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/). Users can select the blocks to add to a Query Loop or single.html template to create the desired front-end layout. The user can modify some attributes (e.g., styling) to fit the needs of their site design.

```[tasklist]
### Tasks
- [x] Expose CPT template as a block
- [x] Expose block variations of blocks containing bound attributes
- [x] Allow using the CPT template as a replacement for the Post Content in the front-end
```

### Data Type Export

Taking inspiration from the [Create Block Theme](https://wordpress.org/plugins/create-block-theme/) plugin, we will build functionality to export the defined data models as a standalone scaffold plugin. The scaffold plugin sets up the CPT/CF as a no-maintenance, data-entry addition to a site.  This feature will:
Generate a separate plugin containing only the custom post types and custom fields defined.
Allow the exported plugin to function independently of the main Create Content Model plugin.
Provide users with a lightweight, purpose-specific plugin that includes only the data structures they need.

- Generate a separate plugin containing only the custom post types and custom fields defined.
- Allow the exported plugin to function independently of the main Create Content Model plugin.
- Provide users with a lightweight, purpose-specific plugin that includes only the data structures they need.

```[tasklist]
### Tasks
- [x] We will represent the CPTs and CFs in a JSON format, aligning with WordPress core practices (e.g., block.json, theme.json).
- [x] Create one JSON file for each set of CPT and CFs
- [x] Develop JSON parser for CPT and CF creation
- [x] Generate a standalone scaffold plugin ZIP file containing only the runtime and defined data types
```

### Documentation

```[tasklist]
### Tasks
- [x] Initial README sufficient for making the repo public.
- [x] Recommended data workflow.
- [x] Export plugin workflow.
- [x] Roadmap for a larger project.
```

TODO: @autumnfjeld
