### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/create-content-model#77]
The functionality we'd love to build next.

```[tasklist]
### Tasks
- [ ] Bulk data entry with [Data Views](https://github.com/WordPress/gutenberg/issues/63128).
- [x] Add support for hidden fields in the Fields UI.
- [ ] Add support for taxonomies and categories.
- [ ] Client side data validation.
- [ ] Work with core to expand block bindings support for more blocks and more.
- [ ] Add to Studio: for example a one-click spin up a Content Model demo in Studio via Blueprints.
```

**Comment by zaguiini** [comment]
>Add support for hidden fields in the data model.

@bacoords isn't the fields UI responsible for hidden fields?

**Comment by autumnfjeld** [comment]
> > Add support for hidden fields in the data model.
> 
> @bacoords isn't the fields UI responsible for hidden fields?

Ah yes!!!   Thanks catching my mistype!! :)

**Comment by worldoptimizer** [comment]
> Are we planning to release the plugin in the WordPress.org repo @autumnfjeld? If so, the sooner we submit it for review, the sooner it will be approved.

Please do, this is pretty great!

**Comment by autumnfjeld** [comment]
> Are we planning to release the plugin in the WordPress.org repo @autumnfjeld? If so, the sooner we submit it for review, the sooner it will be approved.

@mrfoxtalbot  The plugin in its current form is a prototype, we didn't plan for a release in the WordPress.org plugin repo.

**Comment by danharper83** [comment]
It would be great to know if this is ever going to be developed / maintained?

Cheers Dan
